project:
  type: website
  output-dir: docs

website:
  title: "EMILIO"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: project.qmd
        text: Projects
      - href: fun.qmd
        text: Personal Interests
      - href: resume.qmd
        text: Resume
        
format:
  html:
    theme: [lux, custom.scss]
    css: styles.css



